### ISSUE TITLE
Add possibility to add a filter

### ISSUE THREAD

**Issue by delx** [aminin/airbrake-bundle#3]
I'd like to call the addFilter function of the Notifier API, but I don't see a way to get the notifier. Is it possible to add a functionality for this?

**Comment by aminin** [comment]
@delx, try something like

```php
    /** @var ContainerInterface $container */
    $container->get('ami_airbrake.notifier')->addFilter(function ($params) {
        // some code here
    });
```

The service `ami_airbrake.notifier` must be in the container if you have set  the `project_key` (see [README](https://github.com/aminin/airbrake-bundle#step-3-configure-the-amiairbrakebundle))

**Comment by delx** [comment]
@aminin Thx a lot for your quick answer. Where do I have to put this code? Do I have to add a service which runs this code on a certain kernel event?

**Comment by aminin** [comment]
@delx, it's up to you
