### ISSUE TITLE
Upgrade airbrake to 0.4.x

### ISSUE THREAD

**Issue by pesseyjulien** [aminin/airbrake-bundle#4]
update composer.json ?

**Comment by aminin** [comment]
The latest version is 0.5.1, so why do you need 0.4.x?

**Comment by aminin** [comment]
@pesseyjulien, use `0.2.0` and `0.3.0` for `airbrake/phpbrake`  `0.4.x` and `0.5.x` each respectively.

**Comment by pesseyjulien** [comment]
Well, I setup this bundle in my project, and when I'm receiving mails from Airbrake, they include the following message :

'This project is using an outdated version of phpbrake (0.3.1). The latest version is 0.4.*.'

This is why I was asking for 0.4.x, but we could make it to 0.5.x if we can then :)

**Comment by pesseyjulien** [comment]
did not see the update before, thanks !
