### ISSUE TITLE
Error for symfony 5.1.2

### ISSUE THREAD

**Issue by cybervoid** [aminin/airbrake-bundle#9]
Description:
Installing this bundle in Symfony 5 errors out with `You have requested a non-existent parameter "kernel.root_dir". Did you mean one of these: "kernel.project_dir", "kernel.cache_dir", "kernel.logs_dir"?`

How to reproduce:
Install symfony the latest and then install this bundle

Possible Solution:
https://github.com/aminin/airbrake-bundle/pull/8

**Comment by cybervoid** [comment]
#8

**Comment by aminin** [comment]
Solved in https://github.com/aminin/airbrake-bundle/pull/8
